### ISSUE TITLE
MJGAvailability not catching containsString:

### ISSUE THREAD

**Issue by otusweb** [mattjgalloway/MJGFoundation#12]
I'm trying to get MJGAvailability working for our project

I added the code below to our pch file

```
#define __IPHONE_OS_VERSION_SOFT_MAX_REQUIRED __IPHONE_7_0
#import "MJGAvailability.h"
```

One of our source file contains a call to -[NSString containsString:] which is not available in iOS7, but I don't get any warning.

**Comment by ashevin** [comment]
I tried

```
[@"moo" containsString:@"m"];
```

and I got the warning.

**Comment by leoujz** [comment]
Both the Enable Modules and Link Frameworks Automatically settings default to YES in new Xcode projects. 
After setting Enable Modules to NO, I got the warning, also got link errors.
After checking the api usage, I set Enable Modules to YES again.

**Comment by kenji21** [comment]
There is a new flags with clang 3.7 : -Wpartial-availability (not present yet in Xcode 7b6), this flags do the job. As Apple already supports availability very nicely for swift (I dont remember WWDC15 video to watch for this), I expect ObjC will also benefits from this.

**Comment by kenji21** [comment]
Xcode 7 GM doesn't support the flag (nor 7.1beta) :

```
/Applications/Xcode-beta.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --Wpartial-availability
clang: error: unsupported option '--Wpartial-availability'
```

:-(

**Comment by mattjgalloway** [comment]
My availability macros don't work since modules. You can turn off modules, but that's not really a very good idea.

We'll just need to petition Apple for a feature that allows us to catch the use of unavailable code!

**Comment by mattjgalloway** [comment]
There's an option for catching use of APIs like this in Infer:
http://fbinfer.com/docs/linters-bug-types.html#UNAVAILABLE_API_IN_SUPPORTED_IOS_SDK
