### ISSUE TITLE
MJGAvailability.h Not working when NS_AVAILABLE_IOS() was used to set API version

### ISSUE THREAD

**Issue by JohnEstropia** [mattjgalloway/MJGFoundation#6]
The deprecation warning works fine for symbols declared with __OSX_AVAILABLE_STARTING but not for those declared with NS_AVAILABLE_IOS and its variants (NS_ENUM_AVAILABLE_IOS, etc.)

**Comment by mattjgalloway** [comment]
Ah only just seen that you posted this. Yes indeed - MJGAvailability really doesn't work well with the iOS 7 SDK. I've been meaning to get round to sorting this out. Apologies.

**Comment by mattgapadmi** [comment]
These seem to all bottom out at CF_AVAILABLE, CF_AVAILABLE_MAC and CF_AVAILABLE_IOS. I've added the following for it to work with ios:

#undef CF_AVAILABLE
#define CF_AVAILABLE(_mac, _ios) __AVAILABILITY_INTERNAL__IPHONE_##_ios
#undef CF_AVAILABLE_IOS
#define CF_AVAILABLE_IOS(_ios) __AVAILABILITY_INTERNAL__IPHONE_##_ios

Any comments?

**Comment by mattjgalloway** [comment]
@mattgapadmi Oh I see, so overriding the CF_AVAILABLE stuff, to bypass the new behaviour. Feel free to PR!

**Comment by Speakus** [comment]
PR here - https://github.com/mattjgalloway/MJGFoundation/pull/9

**Comment by mattjgalloway** [comment]
Fixed in #9

**Comment by keithyipkw** [comment]
Does it work in Xcode 6.1.1 (6A2008a)? NS_AVAILABLE_IOS seems to only work fine in my code but not in iOS library.

**Comment by keithyipkw** [comment]
Setting "Enable Modueles" in build settings solve my issue. The solution is in #9 #11
