### ISSUE TITLE
Luminosity in UIColor returns infinity

### ISSUE THREAD

**Issue by dinarajas** [mattjgalloway/MJGFoundation#7]
In `UIColor-Additions` category, method for `luminosityDifference:` returns **infinity** for black color when combine with certain colors.

**Comment by mattjgalloway** [comment]
Thanks. I'll take a look. Or if you feel like it - send me a PR.

**Comment by robertmryan** [comment]
@mattjgalloway I was about to post a new issue, but stumbled across this one, so I thought I'd chime in. The luminosity difference calculation in [`UIColor-MJGAdditions`](https://github.com/mattjgalloway/MJGFoundation/blob/master/Source/Categories/UIColor/UIColor-MJGAdditions.m) has final calculation of the difference in `luminosityDifference`:

```
if (l1 > l2) {
    return (l1+0.05f) / (l2/0.05f);
} else {
    return (l2+0.05f) / (l1/0.05f);
}
```

I assume you intended:

```
if (l1 > l2) {
    return (l1+0.05f) / (l2+0.05f);
} else {
    return (l2+0.05f) / (l1+0.05f);
}
```

**Comment by robertmryan** [comment]
@mattjgalloway 

As an aside, I might also suggest getting the components using `UIColor` method `getRed:blue:green:alpha:` rather than `CGColorGetComponents`. This way, if the color happens to be in another color space (e.g. HSB), you still have a fighting chance because this method converts to RGB if it can. Also, I might suggest handling B&W, too, by checking `getWhite:alpha:` if `getRed:blue:green:alpha:` fails (and standard colors like `[UIColor lightGrayColor]` or `[UIColor darkGrayColor]` would fail with the original algorithm). Thus, perhaps something like:

```
- (float)luminosity {
    CGFloat red;
    CGFloat green;
    CGFloat blue;
    CGFloat alpha;

    BOOL success = [self getRed:&red green:&green blue:&blue alpha:&alpha];
    if (success)
        return 0.2126 * pow(red, 2.2f) + 0.7152 * pow(green, 2.2f) + 0.0722 * pow(blue, 2.2f);

    CGFloat white;

    success = [self getWhite:&white alpha:&alpha];
    if (success)
        return pow(white, 2.2f);

    return -1;
}

- (float)luminosityDifference:(UIColor*)otherColor {
    float l1 = [self luminosity];
    float l2 = [otherColor luminosity];

    if (l1 >= 0 && l2 >= 0) {
        if (l1 > l2) {
            return (l1+0.05f) / (l2+0.05f);
        } else {
            return (l2+0.05f) / (l1+0.05f);
        }
    }

    return 0.0f;
}
```

**Comment by mattjgalloway** [comment]
@robertmryan Thanks for the comments! I think `getRed:blue:green:alpha:` is fairly new right? I did this before that.

Any chance you can knock these 2 things into a pull request? Would be ace!

**Comment by robertmryan** [comment]
I put the formula typo in a separate commit from the broader change to the luminosity algorithm, so you could pick and choose (in case you weren't comfortable with the min iOS 5 constraint the `getRed:green:blue:alpha:` method introduced).

**Comment by robertmryan** [comment]
Clearly, you could use `respondsToSelector` and use your old algorithm if you need to support iOS versions prior to 5.
